### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by joepie91** [joshuacaron/parse-katex#1]
In [this part of the code](https://github.com/joshuacaron/parse-katex/blob/master/main.js#L5-L6), the following is stated about the 'Ž' character:

> Useless character that is unlikely to be typed.

The Ž is a normal letter in the Croatian alphabet, that now can't be used by users of this module, without corrupting their data. Using it like this is not acceptable from an internationalization point of view (and the same goes for any other character).

Rather than using 'special values' for escaping, you should use a proper escape sequence, eg. prefixing with a backslash.

**Comment by joshuacaron** [comment]
I had actually forgotten I did that, it was just supposed to be a temporary measure since I needed the code to work and was getting annoyed by the lack of lookbehind in regex in javascript. I fixed it so that it directly deals with the delimiting instead of switching to another character, so there shouldn't be a problem now. I will post a new version to npm shortly.
